name: A Yellow Guard
favicon: null
layout_spectrum: 0.71411
typography_spectrum: 0.43225
title: A Yellow Guard - idle speculation from a highly uninformed source
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0716'
    - '#372d61'
    - '#a89fce'
    - '#fdfdfd'
    - '#febda3'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
