name: A Yellow Guard
favicon: null
layout_spectrum: 0.43934
typography_spectrum: 0.6037774260621518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fbc03b'
    - '#191c23'
    - '#747474'
    - '#d4d4d4'
  brandStrength: 0.0035746132489293814
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.30911181564442813
purpose: []
