title: A Yellow Guard - idle speculation from a highly uninformed source
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.125
  brandStrength: 0.7544803
  lightness: 0.3125
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#FCC128'
    - '#909090'
    - '#8FCC01'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: A Yellow Guard
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.43225
layout_spectrum: 0.45134
